#+TITLE: Ejercicios de lógica de primer orden con Lean
#+AUTHOR: José A. Alonso
#+OPTIONS: ^:nil
#+OPTIONS: num:t
#+OPTIONS: :makeindex
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./estilo.css" />
#+LATEX_CLASS: book-noparts
#+LATEX_CLASS_OPTIONS: [a4paper,12pt,twoside]
#+LATEX_HEADER:\usepackage{makeidx}
#+LATEX_HEADER:\makeindex

# * Contenido                                                             :TOC:

#+LATEX: \input Ejercicios_de_LPO_con_Lean_Preambulo

* Introducción

Este libro es una colección de soluciones de ejercicios de lógica de primer
orden (LPO) formalizadas con [[https://leanprover-community.github.io/][Lean]] que complementa el libro de [[https://github.com/jaalonso/Logica_con_Lean/raw/master/Logica_con_Lean.pdf][Lógica con Lean]] y
es continuación del libro [[https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/Ejercicios_de_LP_con_Lean.pdf][Ejercicios de lógica proposicional con Lean]].

Para cada uno de los ejercicios se formalizan las soluciones en distintos
estilos:
+ aplicativo usando tácticas con razonamiento hacia atrás,
+ declarativo (o estructurado) con razonamiento hacia adelante,
+ funcional con términos del tipo especificado y
+ automático.

Las demostraciones funcionales se obtienen mediante una sucesión de
transformaciones de una aplicativa (o declarativa) eliminando elementos no
esenciales.

Además, al final de cada ejercicio se encuentra un enlace al código y otro a una
sesión de Lean en la Web que contiene la solución del ejercicio.

* Ejercicios sobre cuantificadores

** ∀x, P x ⟶ Q x ⊢ (∀x, P x) ⟶ (∀x, Q x)
   #+INCLUDE: "./src/2_LPO/Ejercicios/∀x,Px⟶Qx⊢(∀x,Px)⟶(∀x,Qx).lean" src lean
   Enlaces al [[./src/2_LPO/Ejercicios/∀x,Px⟶Qx⊢(∀x,Px)⟶(∀x,Qx).lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/∀x,Px⟶Qx⊢(∀x,Px)⟶(∀x,Qx).lean][sesión en Lean Web]].

*** ∃ x, ¬(P x) ⊢ ¬(∀ x, P x)
    Enlaces al [[./src/2_LPO/Ejercicios/∃x,¬(Px)⊢¬(∀x.Px).lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/∃x,¬(Px)⊢¬(∀x.Px).lean][sesión en Lean Web]].
    #+INCLUDE: "./src/2_LPO/Ejercicios/∃x,¬(Px)⊢¬(∀x.Px).lean" src lean

** ∀ x, P x ⊢ ∀ y, P y
   #+INCLUDE: "./src/2_LPO/Ejercicios/∀x,Px⊢∀y,Py.lean" src lean
   Enlaces al [[./src/2_LPO/Ejercicios/∀x,Px⊢∀y,Py.lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/∀x,Px⊢∀y,Py.lean][sesión en Lean Web]].

** ∀ x, P x → Q x ⊢ (∀ x, ¬(Q x)) → (∀ x, ¬(P x))
   #+INCLUDE: "./src/2_LPO/Ejercicios/∀x,Px→Qx⊢(∀ x,¬(Qx))→(∀ x,¬(Px)).lean" src lean
   Enlaces al [[./src/2_LPO/Ejercicios/∀x,Px→Qx⊢(∀ x,¬(Qx))→(∀ x,¬(Px)).lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/∀x,Px→Qx⊢(∀ x,¬(Qx))→(∀ x,¬(Px)).lean][sesión en Lean Web]].

** ∀ x, P x → ¬(Q x) ⊢ ¬(∃ x, P x ∧ Q x)
   #+INCLUDE: "./src/2_LPO/Ejercicios/∀x,Px→¬(Qx)⊢¬(∃x,Px∧Qx).lean" src lean
   Enlaces al [[./src/2_LPO/Ejercicios/∀x,Px→¬(Qx)⊢¬(∃x,Px∧Qx).lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/∀x,Px→¬(Qx)⊢¬(∃x,Px∧Qx).lean][sesión en Lean Web]].

** ∀ x y, P x y ⊢ ∀ u v, P u v
   #+INCLUDE: "./src/2_LPO/Ejercicios/∀ x y, P x y ⊢ ∀ u v, P u v.lean" src lean
   Enlaces al [[./src/2_LPO/Ejercicios/∀ x y, P x y ⊢ ∀ u v, P u v.lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/∀ x y, P x y ⊢ ∀ u v, P u v.lean][sesión en Lean Web]].

** ∃ x y, P x y ⊢ ∃ u v, P u v
   #+INCLUDE: "./src/2_LPO/Ejercicios/∃ x y, P x y ⊢ ∃ u v. P u v.lean" src lean
   Enlaces al [[./src/2_LPO/Ejercicios/∃ x y, P x y ⊢ ∃ u v. P u v.lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/∃ x y, P x y ⊢ ∃ u v. P u v.lean][sesión en Lean Web]].

** ∃ x, ∀ y, P x y ⊢ ∀ y, ∃ x, P x y
   #+INCLUDE: "./src/2_LPO/Ejercicios/∃ x, ∀ y, P x y ⊢ ∀y, ∃ x, P x y.lean" src lean
   Enlaces al [[./src/2_LPO/Ejercicios/∃ x, ∀ y, P x y ⊢ ∀y, ∃ x, P x y.lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/∃ x, ∀ y, P x y ⊢ ∀y, ∃ x, P x y.lean][sesión en Lean Web]].

** ∃x, P a → Q x ⊢ P a → (∃ x, Q x)
   #+INCLUDE: "./src/2_LPO/Ejercicios/∃x, P a → Q x ⊢ P a → (∃ x, Q x).lean" src lean
   Enlaces al [[./src/2_LPO/Ejercicios/∃x, P a → Q x ⊢ P a → (∃ x, Q x).lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/∃x, P a → Q x ⊢ P a → (∃ x, Q x).lean][sesión en Lean Web]].

** P a → (∃ x, Q x) ⊢ ∃ x, P a → Q x
   #+INCLUDE: "./src/2_LPO/Ejercicios/P a → (∃ x, Q x) ⊢ ∃ x, P a → Q x.lean" src lean
   Enlaces al [[./src/2_LPO/Ejercicios/P a → (∃ x, Q x) ⊢ ∃ x, P a → Q x.lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/P a → (∃ x, Q x) ⊢ ∃ x, P a → Q x.lean][sesión en Lean Web]].

** P a → (∃ x, Q x) ⊢ ∃ x, P a → Q x
   #+INCLUDE: "./src/2_LPO/Ejercicios/P a → (∃ x, Q x) ⊢ ∃ x, P a → Q x.lean" src lean
   Enlaces al [[./src/2_LPO/Ejercicios/P a → (∃ x, Q x) ⊢ ∃ x, P a → Q x.lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/P a → (∃ x, Q x) ⊢ ∃ x, P a → Q x.lean][sesión en Lean Web]].

** (∃ x, P x) → Q a ⊢ ∀ x, P x → Q a
   #+INCLUDE: "./src/2_LPO/Ejercicios/(∃ x, P x) → Q a ⊢ ∀ x, P x → Q a.lean" src lean
   Enlaces al [[./src/2_LPO/Ejercicios/(∃ x, P x) → Q a ⊢ ∀ x, P x → Q a.lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/(∃ x, P x) → Q a ⊢ ∀ x, P x → Q a.lean][sesión en Lean Web]].

** ∀ x, P x → Q a ⊢ ∃ x, P x → Q a
   #+INCLUDE: "./src/2_LPO/Ejercicios/∀ x, P x → Q a ⊢ ∃ x, P x → Q a.lean" src lean
   Enlaces al [[./src/2_LPO/Ejercicios/∀ x, P x → Q a ⊢ ∃ x, P x → Q a.lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/∀ x, P x → Q a ⊢ ∃ x, P x → Q a.lean][sesión en Lean Web]].

** (∀ x, P x) ∨ (∀ x, Q x) ⊢ ∀ x, P x ∨ Q x
   #+INCLUDE: "./src/2_LPO/Ejercicios/(∀ x, P x) ∨ (∀ x, Q x) ⊢ ∀ x, P x ∨ Q x.lean" src lean
   Enlaces al [[./src/2_LPO/Ejercicios/(∀ x, P x) ∨ (∀ x, Q x) ⊢ ∀ x, P x ∨ Q x.lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/(∀ x, P x) ∨ (∀ x, Q x) ⊢ ∀ x, P x ∨ Q x.lean][sesión en Lean Web]].

** ∃ x, P x ∧ Q x ⊢ (∃ x, P x) ∧ (∃ x, Q x)
   #+INCLUDE: "./src/2_LPO/Ejercicios/∃ x, P x ∧ Q x ⊢ (∃ x, P x) ∧ (∃ x, Q x).lean" src lean
   Enlaces al [[./src/2_LPO/Ejercicios/∃ x, P x ∧ Q x ⊢ (∃ x, P x) ∧ (∃ x, Q x).lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/∃ x, P x ∧ Q x ⊢ (∃ x, P x) ∧ (∃ x, Q x).lean][sesión en Lean Web]].

** ∀ x y, P y → Q x ⊢ (∃ y, P y) → (∀ x, Q x)
   #+INCLUDE: "./src/2_LPO/Ejercicios/∀ x y, P y → Q x ⊢ (∃ y, P y) → (∀ x, Q x).lean" src lean
   Enlaces al [[./src/2_LPO/Ejercicios/∀ x y, P y → Q x ⊢ (∃ y, P y) → (∀ x, Q x).lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/∀ x y, P y → Q x ⊢ (∃ y, P y) → (∀ x, Q x).lean][sesión en Lean Web]].

** ¬(∀ x, ¬(P x)) ⊢ ∃ x, P x
   #+INCLUDE: "./src/2_LPO/Ejercicios/¬(∀ x, ¬(P x)) ⊢ ∃ x, P x.lean" src lean
   Enlaces al [[./src/2_LPO/Ejercicios/¬(∀ x, ¬(P x)) ⊢ ∃ x, P x.lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/¬(∀ x, ¬(P x)) ⊢ ∃ x, P x.lean][sesión en Lean Web]].

** ∀ x, ¬(P x) ⊢ ¬(∃ x, P x)
   #+INCLUDE: "./src/2_LPO/Ejercicios/∀ x, ¬(P x) ⊢ ¬(∃ x, P x).lean" src lean
   Enlaces al [[./src/2_LPO/Ejercicios/∀ x, ¬(P x) ⊢ ¬(∃ x, P x).lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/∀ x, ¬(P x) ⊢ ¬(∃ x, P x).lean][sesión en Lean Web]].

** ∃ x, P x ⊢ ¬(∀ x, ¬(P x))
   #+INCLUDE: "./src/2_LPO/Ejercicios/∃ x, P x ⊢ ¬(∀ x, ¬(P x)).lean" src lean
   Enlaces al [[./src/2_LPO/Ejercicios/∃ x, P x ⊢ ¬(∀ x, ¬(P x)).lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/∃ x, P x ⊢ ¬(∀ x, ¬(P x)).lean][sesión en Lean Web]].

** P a → (∀ x, Q x) ⊢ ∀ x, P a → Q x
   #+INCLUDE: "./src/2_LPO/Ejercicios/P a → (∀ x, Q x) ⊢ ∀ x, P a → Q x.lean" src lean
   Enlaces al [[./src/2_LPO/Ejercicios/P a → (∀ x, Q x) ⊢ ∀ x, P a → Q x.lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/P a → (∀ x, Q x) ⊢ ∀ x, P a → Q x.lean][sesión en Lean Web]].

** ∀ x y z, R x y ∧ R y z → R x z; ∀ x, ¬(R x x) ⊢ ∀ x y, R x y → ¬(R y x)
   #+INCLUDE: "./src/2_LPO/Ejercicios/∀ x y z, R x y ∧ R y z → R x z, ∀ x, ¬(R x x) ⊢ ∀ x y, R x y → ¬(R y x).lean" src lean
   Enlaces al [[./src/2_LPO/Ejercicios/∀ x y z, R x y ∧ R y z → R x z, ∀ x, ¬(R x x) ⊢ ∀ x y, R x y → ¬(R y x).lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/∀ x y z, R x y ∧ R y z → R x z, ∀ x, ¬(R x x) ⊢ ∀ x y, R x y → ¬(R y x).lean][sesión en Lean Web]].

** ∀x, P x ∨ Q x; ∃x, ¬Q x, ∀ x, R x → ¬P x ⊢ ∃x, ¬R x
   #+INCLUDE: "./src/2_LPO/Ejercicios/∀x, P x ∨ Q x; ∃x, ¬Q x, ∀ x, R x → ¬P x ⊢ ∃x, ¬R x.lean" src lean
   Enlaces al [[./src/2_LPO/Ejercicios/∀x, P x ∨ Q x; ∃x, ¬Q x, ∀ x, R x → ¬P x ⊢ ∃x, ¬R x.lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/∀x, P x ∨ Q x; ∃x, ¬Q x, ∀ x, R x → ¬P x ⊢ ∃x, ¬R x.lean][sesión en Lean Web]].

** ∀x, P x → Q x ∨ R x; ¬∃x, P x ∧ R x ⊢ ∀x, P x → Q x
   #+INCLUDE: "./src/2_LPO/Ejercicios/∀x, P x → Q x ∨ R x; ¬∃x, P x ∧ R x ⊢ ∀x, P x → Q x.lean" src lean
   Enlaces al [[./src/2_LPO/Ejercicios/∀x, P x → Q x ∨ R x; ¬∃x, P x ∧ R x ⊢ ∀x, P x → Q x.lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/∀x, P x → Q x ∨ R x; ¬∃x, P x ∧ R x ⊢ ∀x, P x → Q x.lean][sesión en Lean Web]].

** ∃ x y, R x y ∨ R y x ⊢ ∃ x y, R x y
   #+INCLUDE: "./src/2_LPO/Ejercicios/∃ x y, R x y ∨ R y x ⊢ ∃ x y, R x y.lean" src lean
   Enlaces al [[./src/2_LPO/Ejercicios/∃ x y, R x y ∨ R y x ⊢ ∃ x y, R x y.lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/∃ x y, R x y ∨ R y x ⊢ ∃ x y, R x y.lean][sesión en Lean Web]].

** (∃x, ∀y, P x y) → (∀y, ∃x, P x y)
   #+INCLUDE: "./src/2_LPO/Ejercicios/(∃x, ∀y, P x y) → (∀y, ∃x, P x y).lean" src lean
   Enlaces al [[./src/2_LPO/Ejercicios/(∃x, ∀y, P x y) → (∀y, ∃x, P x y).lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/(∃x, ∀y, P x y) → (∀y, ∃x, P x y).lean][sesión en Lean Web]].

** (∀ x, P x → Q) ⟷ ((∃x, P x) → Q)
   #+INCLUDE: "./src/2_LPO/Ejercicios/(∀ x, P x → Q) ⟷ ((∃x, P x) → Q).lean" src lean
   Enlaces al [[./src/2_LPO/Ejercicios/(∀ x, P x → Q) ⟷ ((∃x, P x) → Q).lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/(∀ x, P x → Q) ⟷ ((∃x, P x) → Q).lean][sesión en Lean Web]].

** ((∀x, P x) ∧ (∀x, Q x)) ⟷ (∀x, P x ∧ Q x)
   #+INCLUDE: "./src/2_LPO/Ejercicios/((∀x, P x) ∧ (∀x, Q x)) ⟷ (∀x, P x ∧ Q x).lean" src lean
   Enlaces al [[./src/2_LPO/Ejercicios/((∀x, P x) ∧ (∀x, Q x)) ⟷ (∀x, P x ∧ Q x).lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/((∀x, P x) ∧ (∀x, Q x)) ⟷ (∀x, P x ∧ Q x).lean][sesión en Lean Web]].

** ((∃x, P x) ∨ (∃x, Q x)) ⟷ (∃x, P x ∨ Q x)
   #+INCLUDE: "./src/2_LPO/Ejercicios/((∃x, P x) ∨ (∃x, Q x)) ⟷ (∃x, P x ∨ Q x).lean" src lean
   Enlaces al [[./src/2_LPO/Ejercicios/((∃x, P x) ∨ (∃x, Q x)) ⟷ (∃x, P x ∨ Q x).lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/((∃x, P x) ∨ (∃x, Q x)) ⟷ (∃x, P x ∨ Q x).lean][sesión en Lean Web]].

** (¬(∀ x, P x)) ⟷ (∃x, ¬P x)
   #+INCLUDE: "./src/2_LPO/Ejercicios/(¬(∀ x, P x)) ⟷ (∃x, ¬P x).lean" src lean
   Enlaces al [[./src/2_LPO/Ejercicios/(¬(∀ x, P x)) ⟷ (∃x, ¬P x).lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/(¬(∀ x, P x)) ⟷ (∃x, ¬P x).lean][sesión en Lean Web]].

* Ejercicios sobre igualdad y funciones

** P a ⊢ ∀ x, x = a → P x
   #+INCLUDE: "./src/2_LPO/Ejercicios/P a ⊢ ∀ x, x ~ a → P x.lean" src lean
   Enlaces al [[./src/2_LPO/Ejercicios/P a ⊢ ∀ x, x ~ a → P x.lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/P a ⊢ ∀ x, x ~ a → P x.lean][sesión en Lean Web]].

** ∃x y, R x y ∨ R y x; ¬∃x, R x x ⊢ ∃x y, x ≠ y
   #+INCLUDE: "./src/2_LPO/Ejercicios/∃x y, R x y ∨ R y x; ¬∃x, R x x ⊢ ∃x y, x ≠ y.lean" src lean
   Enlaces al [[./src/2_LPO/Ejercicios/∃x y, R x y ∨ R y x; ¬∃x, R x x ⊢ ∃x y, x ≠ y.lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/∃x y, R x y ∨ R y x; ¬∃x, R x x ⊢ ∃x y, x ≠ y.lean][sesión en Lean Web]].

** ∀x, P a x x; ∀xyz, P x y z → P (f x) y (f z) ⊢ P (f a) a (f a)
   #+INCLUDE: "./src/2_LPO/Ejercicios/∀x, P a x x; ∀xyz, P x y z → P (f x) y (f z) ⊢ P (f a) a (f a).lean" src lean
   Enlaces al [[./src/2_LPO/Ejercicios/∀x, P a x x; ∀xyz, P x y z → P (f x) y (f z) ⊢ P (f a) a (f a).lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/∀x, P a x x; ∀xyz, P x y z → P (f x) y (f z) ⊢ P (f a) a (f a).lean][sesión en Lean Web]].

** ∀x, P a x x; ∀xyz, P x y z → P (f x) y (f z) ⊢ ∃z, P (f a) z (f (f a))
   #+INCLUDE: "./src/2_LPO/Ejercicios/∀x, P a x x; ∀xyz, P x y z → P (f x) y (f z) ⊢ ∃z, P (f a) z (f (f a)).lean" src lean
   Enlaces al [[./src/2_LPO/Ejercicios/∀x, P a x x; ∀xyz, P x y z → P (f x) y (f z) ⊢ ∃z, P (f a) z (f (f a)).lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/∀x, P a x x; ∀xyz, P x y z → P (f x) y (f z) ⊢ ∃z, P (f a) z (f (f a)).lean][sesión en Lean Web]].

** ∀y, Q a y; ∀xy, Q x y → Q (s x) (s y) ⊢ ∃z, Qa z ∧ Q z (s (s a))
   #+INCLUDE: "./src/2_LPO/Ejercicios/∀y, Q a y; ∀xy, Q x y → Q (s x) (s y) ⊢ ∃z, Qa z ∧ Q z (s (s a)).lean" src lean
   Enlaces al [[./src/2_LPO/Ejercicios/∀y, Q a y; ∀xy, Q x y → Q (s x) (s y) ⊢ ∃z, Qa z ∧ Q z (s (s a)).lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/∀y, Q a y; ∀xy, Q x y → Q (s x) (s y) ⊢ ∃z, Qa z ∧ Q z (s (s a)).lean][sesión en Lean Web]].

** x = f x; P (f x) ⊢ P x
   #+INCLUDE: "./src/2_LPO/Ejercicios/x ~ f x; P (f x) ⊢ P x.lean" src lean
   Enlaces al [[./src/2_LPO/Ejercicios/x ~ f x; P (f x) ⊢ P x.lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/x ~ f x; P (f x) ⊢ P x.lean][sesión en Lean Web]].

** x = f x, triple (f x) (f x) x ⊢ triple x x x
   #+INCLUDE: "./src/2_LPO/Ejercicios/x ~ f x, triple (f x) (f x) x ⊢ triple x x x.lean" src lean
   Enlaces al [[./src/2_LPO/Ejercicios/x ~ f x, triple (f x) (f x) x ⊢ triple x x x.lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/2_LPO/Ejercicios/x ~ f x, triple (f x) (f x) x ⊢ triple x x x.lean][sesión en Lean Web]].

* Bibliografía

+ [[https://www.cs.us.es/~jalonso/cursos/li/temas/tema-8.pdf][Deducción natural en lógica de primer orden]]. ~ J.A. Alonso, A. Cordón, M.J. Hidalgo.
+ [[https://github.com/jaalonso/Logica_con_Lean/raw/master/Logica_con_Lean.pdf][Lógica con Lean]] ~ J.A. Alonso.
  + Cap. 2: Lógica proposicional.
+ [[https://leanprover.github.io/logic_and_proof/][Logic and proof]]. ~ J. Avigad, R.Y. Lewis, F. van Doorn.
  + Cap. 4: Propositional Logic in Lean.
+ [[https://books.google.es/books?id=eUggAwAAQBAJ&lpg=PP1&dq=inauthor%3A%22Michael%20Huth%22&hl=es&pg=PP5#v=onepage&q&f=false][Logic in Computer Science]]. ~ M. Huth, M. Ryan.
  + Cap. 1.2: Propositional logic. Natural deduction.
+ [[https://leanprover.github.io/theorem_proving_in_lean/][Theorem proving in Lean]]. ~ J. Avigad, L. de Moura, S. Kong.
  + Cap. 3: Propositions and proofs.


# #+LATEX:\printindex
#+LATEX: \end{document}
