#+TITLE: Ejercicios de lógica proposicional con Lean
#+AUTHOR: José A. Alonso
#+OPTIONS: ^:nil
#+OPTIONS: num:t
#+OPTIONS: :makeindex
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./estilo.css" />
#+LATEX_CLASS: book-noparts
#+LATEX_CLASS_OPTIONS: [a4paper,12pt,twoside]
#+LATEX_HEADER:\usepackage{makeidx}
#+LATEX_HEADER:\makeindex

# * Contenido                                                             :TOC:

#+LATEX: \input Ejercicios_de_logica_proposicional_con_Lean_Preambulo

* Introducción

Este libro es una colección de soluciones de ejercicios de lógica proposicional
formalizadas con [[https://leanprover-community.github.io/][Lean]] que complementa el libro de [[https://github.com/jaalonso/Logica_con_Lean/raw/master/Logica_con_Lean.pdf][Lógica con Lean]].

En cada capítulo va entrando en juego una nueva
conectiva y para cada uno de los ejercicios se formalizan las soluciones en
distintos estilos:
+ aplicativo usando tácticas con razonamiento hacia atrás,
+ declarativo (o estructurado) con razonamiento hacia adelante,
+ funcional con términos del tipo especificado y
+ automático.

Además, al final de cada ejercicio se encuentra un enlace al código y otro a una
sesión de Lean en la Web que contiene la solución del ejercicio.

* Ejercicios sobre implicaciones

** p ⟶ q, p ⊢ q
   #+INCLUDE: "./src/1_Proposicional/Ejercicios/Pruebas_de_p_⟶_q,_p ⊢_q.lean" src lean
   Enlaces al [[./src/1_Proposicional/Ejercicios/Pruebas_de_p_⟶_q,_p ⊢_q.lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/1_Proposicional/Ejercicios/Pruebas_de_p_⟶_q,_p ⊢_q.lean][sesión en Lean Web]]. y al vídeo.

** p → q, q → r, p ⊢ r
   #+INCLUDE: "./src/1_Proposicional/Ejercicios/p→q,q→r,p⊢r.lean" src lean
   Enlaces al [[./src/1_Proposicional/Ejercicios/p→q,q→r,p⊢r.lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/1_Proposicional/Ejercicios/p→q,q→r,p⊢r.lean][sesión en Lean Web]].

** p → (q → r), p → q, p ⊢ r
   #+INCLUDE: "./src/1_Proposicional/Ejercicios/p→(q→r),p→q,p⊢r.lean" src lean
   Enlaces al [[./src/1_Proposicional/Ejercicios/p→(q→r),p→q,p⊢r.lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/1_Proposicional/Ejercicios/p→(q→r),p→q,p⊢r.lean][sesión en Lean Web]].

** p → q, q → r ⊢ p → r
   #+INCLUDE: "./src/1_Proposicional/Ejercicios/p→q,q→r⊢p→r.lean" src lean
   Enlaces al [[./src/1_Proposicional/Ejercicios/p→q,q→r⊢p→r.lean][código]] y a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/1_Proposicional/Ejercicios/p→q,q→r⊢p→r.lean][sesión en Lean Web]].


# *** Todos los ejercicios
# + Enlaces al [[./src/1_Proposicional/Ejercicios/Ejercicios_de_logica_proposicional.lean][código]], a la [[https://www.cs.us.es/~jalonso/lean-web-editor/#url=https://raw.githubusercontent.com/jaalonso/Logica_con_Lean/master/src/1_Proposicional/Ejercicios/Ejercicios_de_logica_proposicional.lean][sesión en Lean Web]] y al vídeo.
# #+INCLUDE: "./src/1_Proposicional/Ejercicios/Ejercicios_de_logica_proposicional.lean" src lean



# #+LATEX:\printindex
#+LATEX: \end{document}
